#ifndef _JOYSTICK_CONTROLLER_CFG_
#define _JOYSTICK_CONTROLLER_CFG_

#define  LOY_STICK_C_SERIAL_DEBUG 1



#define JOYSTICK_A_X_AXIS_PIN A0
#define JOYSTICK_A_Y_AXIS_PIN A0
#define JOYSTICK_A_SW_PIN     1


#define JOYSTICK_B_X_AXIS_PIN A0
#define JOYSTICK_B_Y_AXIS_PIN A0
#define JOYSTICK_B_SW_PIN     1

#define MAX_ADC_READING  255
#define ZERO_ADC_READING 128
#define MIN_ADC_READING  0

#define MAX_MAP_READING      255
#define ZERO_MAP_READING     0
#define MIN_MAP_READING     -255
#endif /*_JOYSTICK_CONTROLLER_CFG_*/
